# Generated by Django 5.0 on 2024-01-19 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_comment_likes_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quote_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
