# Generated by Django 5.0 on 2024-01-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blog_blog_body_blog_introduction_blog_para_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='para_1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='para_2',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='para_3',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='para_4',
            field=models.TextField(max_length=1000),
        ),
    ]
